### PR TITLE
Update default controllers and requests to meet PHPStan Level 9 standards

### PR DESCRIPTION
**Pull request by JohnnyWalkerDigital**
The default Laravel framework meets [PHPStan](https://phpstan.org/) level 9 standards, but Laravel Breeze currently does not. This is an attempt to bring the default installation up to those standards.

### CODE REVIEW

**Comment by JohnnyWalkerDigital** [comment]
Very confused as to why the tests didn't pass. They're passing fine on my localhost (with Laravel Sail).

**Comment by fabpl** [comment]
Hi,
User model is in App\Models namespace, not App\

**Comment by driesvints** [comment]
Feel free to resend this once you figure out the tests 👍

**Comment by JohnnyWalkerDigital** [comment]
Thanks. Been incredibly busy on other projects. Will get back to this when I can!

**Comment by JohnnyWalkerDigital** [comment]
> Hi, User model is in App\Models namespace, not App\

Ah, I move my models into App\ and forgot to change the reference for this PR. Thanks for spotting.

**Pull request closed without merging**
