### PR TITLE
[1.x] Add email (username) autocomplete

### PR DESCRIPTION
**Pull request by claudiodekker**
As recommended by:
- https://www.chromium.org/developers/design-documents/create-amazing-password-forms
- https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

In addition to Chromium (Edge, Safari, Chrome, Brave, etc.) this is also useful for password managers, as it tells them what fields can be designated to be used in a certain way.

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by taylorotwell** [comment]
We have some conflicts on this PR.

**Comment by claudiodekker** [comment]
@taylorotwell Done!

**Comment by driesvints** [comment]
@claudiodekker can you rebase instead next time? That way the commit history stays clean.

**Comment by claudiodekker** [comment]
@driesvints Of course, do you want me to do that now, followed by a force-push? Shouldn't take too much effort!

**Comment by driesvints** [comment]
@claudiodekker feel free to 👍

**Comment by claudiodekker** [comment]
Haha, too late.. Well, I'll keep it in mind for next time 👍

**Pull request merged**
