### PR TITLE
[2.x] Add option to install ESLint with Prettier

### PR DESCRIPTION
**Pull request by avosalmon**
CleanShot 2024-09-12 at 09 55 53

This PR introduces an option to install and configure ESLint with Prettier for the Inertia stacks.
Selecting the `ESLint with Prettier` option will install ESLint and Prettier with some relevant plugins and add config files.

- It still uses ESLint 8 because some plugins don’t support ESLint 9 flat config yet.
  - e.g. https://github.com/facebook/react/issues/28313
- It adds the `lint` node script to package.json
- This PR also adds a CI workflow to run Pint and ESLint and then commit the coding style changes.

> [!NOTE]  
> Most of the changes for the stubs are code style changes by CI (14759fc864a37a7374de23c88af4336910bb7a25, 60a5a2a48e9ba8df8628c283b448a35344c645dd). Following the commit logs would make it easier to review the changes rather than diving into the files changed.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks!

**Comment by hafezdivandari** [comment]
This has messed up the CI. cc @crynobone @driesvints 

image

**Comment by kjjd84** [comment]
this introduced a ton of deprecation warnings to any apps that use this option

**Comment by avosalmon** [comment]
@kjjd84 Can you elaborate on what kind of deprecation warnings you got?

**Comment by kjjd84** [comment]
> @kjjd84 Can you elaborate on what kind of deprecation warnings you got?

```console
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
```

**Comment by avosalmon** [comment]
@kjjd84 The warnings are coming from `eslint^8.57.0`. However, we are not able to upgrade to ESLint 9 because some of the plugins don't support it yet. We will upgrade ESLint once all the plugins are ready for ESLint 9.

```
npm install -D eslint@^8.57.0
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
```

**Comment by kjjd84** [comment]
> @kjjd84 The warnings are coming from `eslint^8.57.0`. However, we are not able to upgrade to ESLint 9 because some of the plugins don't support it yet. We will upgrade ESLint once all the plugins are ready for ESLint 9.
> 
> ```
> npm install -D eslint@^8.57.0
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
> npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
> ```

right but the old version of eslint has packages that literally leak memory. no offense to you personally but i dont think this should have been merged. its very off-putting when you see warnings after a fresh install of an official laravel package.

**Comment by avosalmon** [comment]
@kjjd84 Vue and Next.js CLIs are also using ESLint 8. I got the same deprecation warnings when I scaffolded Vue and Next apps. It's unavoidable during the transition period. We will upgrade to ESLint 9 as soon as they migrate to ESLint 9.

**Comment by whoami15** [comment]
@avosalmon I noticed that when using the Laravel installer, the "ESLint with Prettier" option is not listed among the optional features. Will this be added there as well?

SCR-20241002-jmkn

**Comment by avosalmon** [comment]
@whoami15 Let me add it to the installer. Thanks for bringing this up!

**Comment by avosalmon** [comment]
@whoami15 It will be available in the next release https://github.com/laravel/installer/pull/361

**Pull request merged**
