### PR TITLE
[1.x] Added Inertia Svelte Stack

### PR DESCRIPTION
**Pull request by 1CAMOU**
Since Inertia v1.0 has been released and Svelte SSR Support added, I thought it'd finally be time to add Svelte as a supported Breeze Stack.

### CODE REVIEW

**Comment by jessarcher** [comment]
Hey @1CAMOU, thanks for your efforts! I'm concerned about maintenance and new feature development going forward, as I don't know if anyone on the Laravel team has much Svelte experience. There can also be quite a lot of work already with just the existing stacks.

**Comment by 1CAMOU** [comment]
> Hey @1CAMOU, thanks for your efforts! I'm concerned about maintenance and new feature development going forward, as I don't know if anyone on the Laravel team has much Svelte experience. There can also be quite a lot of work already with just the existing stacks.

Hi! I can understand your concerns  but just for the reference - this PR was made in just one day and it's pretty much the same as the other stacks as far as i can see - I believe Svelte is great because of it's simplicity but of course you guys will know if this is a good idea or not, I enjoyed working on this and I would certainly enjoy putting further work into a Svelte Stack :)

**Comment by taylorotwell** [comment]
Thanks for sending this in - I may come back to it at some point as a reference. But, for now, perhaps make your own `breeze-svelte` repository on your own GitHub account. 🤘

**Comment by weavdale** [comment]
I would love to see this reopened and released.

**Pull request closed without merging**
