### PR TITLE
Add picocolors to devDepedencies

### PR DESCRIPTION
**Pull request by holiq**
When i install breeze with yarn, when i run yarn build i got error can't find module picocolors, after I re-installed picocolors, I can only run yarn build as shown below 
 
Screenshot_20221028-183927_Termux

### CODE REVIEW

**Comment by driesvints** [comment]
We believe this is a bug with Vite itself. @jessarcher and @timacdonald are investigating this.

**Comment by holiq** [comment]
Okay, then what should I do about this PR?

**Comment by driesvints** [comment]
Wait until they respond.

**Comment by timacdonald** [comment]
This is an upstream bug that has should have been addressed in Vite 3.2.1

**Comment by holiq** [comment]
Okay, thanks for the response @timacdonald

**Pull request closed without merging**
