### PR TITLE
Auto update changelog on release

### PR DESCRIPTION
**Pull request by driesvints**
Trying out the auto updater for a Changelog by @stefanzweifel on Breeze. If this goes well, I'll roll this out to every repo.

Could potentially save me quite a bit of time while doing release 🤞

### CODE REVIEW

**Comment by stefanzweifel** [comment]
@driesvints Let me know if something breaks or could be improved.

**Comment by driesvints** [comment]
@stefanzweifel seems like that's not working: https://github.com/laravel/breeze/runs/4793380384?check_suite_focus=true

I also accidentally updated the Changelog already beforehand. Maybe that's the reason it failed?

**Comment by stefanzweifel** [comment]
@driesvints The workflow seems to have failed due to a missing `latest-version` input.

> No latest-version option provided. Abort.  

But I assume you haven't changed [the name](https://github.com/laravel/breeze/releases/tag/v1.7.0) after the release has been published.

You also use different branch options/inputs than [the example](https://github.com/stefanzweifel/changelog-updater-action#usage) in the repo.

Instead of `${{ github.ref_name }}` you could use `master` directly. 

```diff
name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
-         ref: ${{ github.ref_name }}
+         ref: master

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
-         branch: ${{ github.ref_name }}
+         branch: ${{ github.ref_name }}
          commit_message: Update CHANGELOG.md
          file_pattern: CHANGELOG.md
```

> I also accidentally updated the Changelog already beforehand. Maybe that's the reason it failed?

Haven't written a test for this case, but the Action should then just prepend it to the changelog and create duplicate entries. (Will add a test for that)

**Comment by driesvints** [comment]
> But I assume you haven't changed the name after the release has been published.

I'm not sure. I usually don't fill in anything because GitHub takes the tag name automatically. Sometimes, for some bizar reason it uses a commit title or PR title as the name. Then I edit it manually to the tag name. Should I always fill this in? Should I not change it anymore after it's set?

> Instead of ${{ github.ref_name }} you could use master directly.

I can't do that because the current stable branch is 1.x and I want to let it change automatically in the future when the stable branch changes. Basically I just want it to use the target branch used when making the release:

Screenshot 2022-01-13 at 12 56 19

Is it not possible to do that?

**Comment by stefanzweifel** [comment]
> I'm not sure. I usually don't fill in anything because GitHub takes the tag name automatically. Sometimes, for some bizar reason it uses a commit title or PR title as the name. Then I edit it manually to the tag name. Should I always fill this in? Should I not change it anymore after it's set?

Letting GitHub generate the tag name is fine.
I meant: Do you fill the "Release title", when creating a new release? Like I set `v1.5.0` in the screenshot below?
(sorry for the confusion)

Screenshot 2022-01-13 at 13 05 15

That's the value inside `${{ github.event.release.name }}` which is passed as `latest-version` to the Action. This `latest-version` input is required by the Action.

If you keep "Release title" usually empty, I think you could use `${{ github.event.release.tag_name }}`. That value is usually a semantic version.

```diff
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
-         latest-version: ${{ github.event.release.name }}
+         latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
```

(Will change this in the docs of the Action. It's probably more intuitive to use `tag_name`)

**Comment by driesvints** [comment]
> I meant: Do you fill the "Release title", when creating a new release? Like I set v1.5.0 in the screenshot below?
(sorry for the confusion)

Yeah that's what I meant as well haha:

> I usually don't fill in anything because GitHub takes the tag name automatically. Sometimes, for some bizar reason it uses a commit title or PR title as the name. Then I edit it manually to the tag name. Should I always fill this in? Should I not change it anymore after it's set?

> If you keep "Release title" usually empty, I think you could use ${{ github.event.release.tag_name }}. That value is usually a semantic version.

Ah that's good to know, that's probably what I need. Thanks!

**Comment by driesvints** [comment]
Hey @stefanzweifel. Attempted this again but this time it's failing because of:

```
INPUT_TAGGING_MESSAGE: 
35
No tagging message supplied. No tag will be added.
36
INPUT_PUSH_OPTIONS: 
37
To https://github.com/laravel/breeze
38
 ! [rejected]        HEAD -> v1.7.1 (already exists)
39
error: failed to push some refs to 'https://github.com/laravel/breeze'
40
hint: Updates were rejected because the tag already exists in the remote.
41
Error: Invalid status code: 1
42
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
43
    at ChildProcess.emit (events.js:210:5)
44
    at maybeClose (internal/child_process.js:1021:16)
45
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
46
  code: 1
47
}
48
Error: Invalid status code: 1
49
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
50
    at ChildProcess.emit (events.js:210:5)
51
    at maybeClose (internal/child_process.js:1021:16)
52
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```


https://github.com/laravel/breeze/runs/4942298324?check_suite_focus=true

**Comment by stefanzweifel** [comment]
@driesvints I've opened a pull request with a fix for this. https://github.com/laravel/breeze/pull/121
The problem was, that the Action tried to push the changed CHANGELOG.md to a `v1.7.1` branch wich does not exist.

**Pull request merged**
