### PR TITLE
[1.x] Logo for Breeze.

### PR DESCRIPTION
**Pull request by mnaderian**
Updated the logo from #7 
Changed it to be just about the same as requested. Hope you like it.

Laravel Breeze Logo

**PS:** _Sorry, I don't wanna impose my design. If you don't like this kind of logo that's completely OK._

### CODE REVIEW

**Comment by taylorotwell** [comment]
Do you have any other ideas for the mark? Something even simpler perhaps?

**Comment by m-naderian** [comment]
Let me make several designs, and send them right here.

**Comment by joelbutcher** [comment]
@m-naderian How about something like this?

laravel-breeze

**Comment by m-naderian** [comment]
@joelbutcher that's beautiful. But the master of the house should like it. 😉

**Comment by taylorotwell** [comment]
Remember that we want absolute design consistency with the existing logos. I can have the person who usually does them do one.

**Comment by mnaderian** [comment]
@taylorotwell I think this is what you wanted:

Breeze Logo

**Pull request closed without merging**
