### PR TITLE
Added new logo for Laravel Breeze

### PR DESCRIPTION
**Pull request by mnaderian**
Created a new logo for Laravel Breeze. Hope you like it.

### CODE REVIEW

**Comment by Mindgamesnl** [comment]
Looks sick!

**Comment by m-naderian** [comment]
@Mindgamesnl, any suggestions to make it look better?

**Comment by FoksVHox** [comment]
> @Mindgamesnl, any suggestions to make it look better?

You could make the text not use New Times Roman, and maybe take some inspiration from the other Laravel Logos, so it feels more Laravel-like, currently, as it as, I feel this isn't "a real laravel logo", hope fully you get my point.

**Comment by m-naderian** [comment]
@FoksVHox thnx for your suggestion. I will do that.

**Comment by taylorotwell** [comment]
We would want all Laravel package logos to look the same.

**Pull request closed without merging**
