### PR TITLE
Always prompt for optional features

### PR DESCRIPTION
**Pull request by reibengu**
Started a new project using Laravel Bootcamp and ran `php artisan breeze:install react` as instructed.

Noticed the installer doesn't prompt for optional features like TypeScript support or Dark mode when stack is set.
It led to confusion and forced me to recreate the project to include these features.

Changed logic to always prompt for optional features and select as default the arguments passed directly like  `php artisan breeze:install react --typescript`.

It might require an extra argument `--no-interaction` for cases when this is run from another script, similar to what composer uses (that can also be a global trait of commands).

### CODE REVIEW

**Comment by reibengu** [comment]
I can add `--no-interaction` to make the tests pass in case you approve the idea.

**Comment by crynobone** [comment]
This break the current expected behaviour with PromptsForMissingArgument contract. You should provide `breeze:install` instead of providing any argument.

**Comment by reibengu** [comment]
> This break the current expected behaviour with PromptsForMissingArgument contract. You should provide `breeze:install` instead of providing any argument.

It's not related to `PromptsForMissingInput` at all, it's related to how the CLI is designed and if it should always ask for the optional arguments or not.

**Comment by taylorotwell** [comment]
We actually don't document passing arguments to this command.

**Pull request closed without merging**
